<?php
include("pageheader.php");
unset($_SESSION["login"]);
?>
        <script>
            location.replace("index.php");
        </script>
        <?php
        include("pagefooter.html");
    ?>